export const BOTAO_CLICADO_SUCCESS = 'BOTAO_CLICADO_SUCCESS';
export const BOTAO_CLICADO_REQUEST = 'BOTAO_CLICADO_REQUEST';
export const BOTAO_CLICADO_FAILURE = 'BOTAO_CLICADO_FAILURE';


export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

export const REGISTER_OR_UPDATE_REQUEST = 'REGISTER_OR_UPDATE_REQUEST';
export const REGISTER_OR_UPDATE_SUCCESS = 'REGISTER_OR_UPDATE_SUCCESS';
export const REGISTER_OR_UPDATE_FAILURE = 'REGISTER_OR_UPDATE_FAILURE';


export const EMAIL_CHANGED = 'EMAIL_CHANGED';
